### ISSUE TITLE
Can't send HTML email

### ISSUE THREAD

**Issue by grantwparks** [zuhito/node-red-contrib-sendgrid#1]
How does one send HTML email with this node?

**Comment by zuhito** [comment]
Current node doesn't support HTML format. Sendgrid moule seems to support HTML format. If you cam chagne the code, pull request is welcomed.

**Comment by grantwparks** [comment]
Thank you for replying so fast.  I would love to take a crack at this as soon as I get the time.  Best wishes.

**Comment by CptanPanic** [comment]
@grantwparks Any progress on this? Would love to have html email.
