### ISSUE TITLE
"Error: Provide at least one of to, cc or bcc"

### ISSUE THREAD

**Issue by babgi7** [zuhito/node-red-contrib-sendgrid#5]
I keep getting this error no matter what I do, I'm not sure what i have done wrong ??

`[{"id":"ecaf8341.6e312","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"b3fd0c2a.369a3","type":"sendgrid","z":"ecaf8341.6e312","from":"","to":"","name":"","content":"text","x":580,"y":380,"wires":[]},{"id":"3d884b11.adc074","type":"template","z":"ecaf8341.6e312","name":"","field":"payload","fieldType":"msg","format":"json","syntax":"mustache","template":"{\n    \"from\": \"example@hotmail.com\",\n    \"to\": \"example2@hotmail.com\",\n    \"topic\": \"Sending with SendGrid\",\n    \"text\": \"text here\"\n}\n","output":"json","x":320,"y":380,"wires":[["b3fd0c2a.369a3"]]},{"id":"f32e788f.ace7c8","type":"inject","z":"ecaf8341.6e312","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":380,"wires":[["3d884b11.adc074"]]}]`

**Comment by zuhito** [comment]
Paths are wrong as follows. Could you modify it?

[Your flow]
msg.payload.from = "example@hotmail.com"
msg.payload.to = "example2@hotmail.com"
msg.payload.topic = Sending with SendGrid"
msg.payload.text = "text here"

[Correct flow]
msg.from = "example@hotmail.com"
msg.to = "example2@hotmail.com"
msg.topic = Sending with SendGrid"
msg.payload = "text here"
