### ISSUE TITLE
Cannot specify multiple to/cc/bcc email addresses

### ISSUE THREAD

**Issue by seandafts** [zuhito/node-red-contrib-sendgrid#6]
Is there a way to send to multiple email addresses? My company is currently sending about 50k email messages/month through this Node and we would like to be able to specify multiple email addresses on the to/cc or bcc line.

**Comment by seandafts** [comment]
I have tried 
> msg.to = "user1@domain.com,user2@domain.com"  // comma separated
and
> msg.to = "user1@domain.com;user2@domain.com" // semi-colon separated

**Comment by zuhito** [comment]
@seandafts Thank you for your feedback. From the commit for v0.1.1, https://github.com/zuhito/node-red-contrib-sendgrid/commit/2117db359621e55fb923a78b5a8b7e6f7174ab90, multiple addresses in to, cc and bcc are supported. Could you check the new node?
